add autocompletion for project commands

diff --git a/settings/extensions/#standard/commands/tools/projectr/ensure_all_commands_executable b/settings/extensions/#standard/commands/tools/projectr/ensure_all_commands_executable
--- a/settings/extensions/#standard/commands/tools/projectr/ensure_all_commands_executable
+++ b/settings/extensions/#standard/commands/tools/projectr/ensure_all_commands_executable
@@ -70,7 +70,7 @@ do
             setopt extended_glob &>/dev/null
             shopt -s globstar &>/dev/null
             shopt -s dotglob &>/dev/null
-            local search_path='"'""$each"'/'"'"'
+            local search_path='"'""$("$PROJECTR_FOLDER/settings/extensions/#standard/commands/tools/string/escape_shell_argument" "$each")"'/'"'"'
             local argument_combination="$search_path/$1"
             while [[ -n "$@" ]]
             do
@@ -89,7 +89,7 @@ do
                             if [[ -z "$1" ]]
                             then
                                 printf "\nThat is a sub folder, not a command\nValid sub-commands are\n" 1>&2
-                                ls -1FL --group-directories-first --color "$each" | sed '"'"'s/^/    /'"'"' 1>&2
+                                ls -1FL --group-directories-first --color "$each" | sed '"'"'s/^/    /'"'"' | sed -E '"'"'s/(\*|@)$/ /'"'"' 1>&2
                                 return 1 # error, no command
                             fi
                             
@@ -108,12 +108,33 @@ do
             if ! [ -z "$each" ]
             then
                 echo "$each"
-                printf "\nI could not find that sub-command ($(basename "$each"))\n" 1>&2
+                printf "\nI could not find that sub-command\n" 1>&2
             fi
             printf "Valid next-arguments would be:\n" 1>&2
             ls -1FL --group-directories-first --color "$search_path" | sed '"'"'s/^/    /'"'"' | sed -E '"'"'s/(\*|@)$/ /'"'"' 1>&2
             return 1 # error, no command
         }
+        __autocomplete_for__'"$name"' () {
+            local commands_path='"'""$("$PROJECTR_FOLDER/settings/extensions/#standard/commands/tools/string/escape_shell_argument" "$PROJECTR_COMMANDS_FOLDER")""'"'
+            # TODO: make this space friendly
+            # TODO: make this do partial-word complete 
+            function join_by { local d=${1-} f=${2-}; if shift 2; then printf %s "$f" "${@/#/$d}"; fi; }
+            local item_path="$(join_by "/" $words)"
+            if [ -d "$commands_path/$item_path" ]
+            then
+                compadd $(ls "$commands_path/$item_path")
+            elif [ -d "$(dirname "$commands_path/$item_path")" ]
+            then
+                # check if file exists (finished completion)
+                if ! [ -f "$commands_path/$item_path" ]
+                then
+                    # TODO: add a better check for sub-matches "java" [tab] when "java" and "javascript" exist
+                    compadd $(ls "$(dirname "$commands_path/$item_path")")
+                fi
+            fi
+            # echo "$(dirname "$commands_path/$item_path")"
+        }
+        compdef __autocomplete_for__'"$name"' '"$name"'
         ' > /dev/null
     fi
 done < "$__temp_var__temp_folder/pipe_for_while_$__NESTED_WHILE_COUNTER";__NESTED_WHILE_COUNTER="$((__NESTED_WHILE_COUNTER - 1))"
