combine underscore and start

diff --git a/commands/start b/commands/start
--- a/commands/start
+++ b/commands/start
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-source ./settings/projectr_core
 
 # 
 # summary
@@ -7,10 +6,47 @@ source ./settings/projectr_core
 #     this file is used to run commands
 #     it loads the PROJECTR env variables first (./settings/projectr_core)
 #     then in looks inside the commands folder for commands to run
-#     (unlike the underscore, this does not load the manual environment)
+#     no arguments will start the automatic environment
+#     providing an argument (ex: clean) will run whatever is under commands/project/ (ex: commands/project/clean)
 
 # 
-# no args
+# find the projectr_core
+# 
+path_to_projectr_core=""
+file_name="settings/projectr_core"
+folder_to_look_in="$PWD"
+while :
+do
+    # check if file exists
+    if [ -f "$folder_to_look_in/$file_name" ]
+    then
+        path_to_projectr_core="$folder_to_look_in/$file_name"
+        break
+    else
+        if [ "$folder_to_look_in" = "/" ]
+        then
+            break
+        else
+            folder_to_look_in="$(dirname "$folder_to_look_in")"
+        fi
+    fi
+done
+if [ -z "$path_to_projectr_core" ]
+then
+    #
+    # what to do if file never found
+    #
+    echo "Im a script running with a pwd of:$PWD"
+    echo "Im looking for settings/projectr_core in a parent folder"
+    echo "Im exiting now because I wasnt able to find it"
+    echo "thats all the information I have"
+    exit
+fi
+source "$path_to_projectr_core"
+
+
+# 
+# if given no args
 # 
 if [[ "$#" = "0" ]]
 then
@@ -20,21 +56,23 @@ then
 # otherwise run the respective project command
 # 
 else
-    absolute_path () {
-        echo "$(builtin cd "$(dirname "$1")"; pwd)/$(basename "$1")"
-    }
+    source "$PROJECTR_COMMANDS_FOLDER/manual_setup"
+    # enable globbing
+    shopt -s globstar &>/dev/null
+    shopt -s dotglob &>/dev/null
+    
     # 
     # recursively drill down
     # 
-    search_path="$PROJECTR_COMMANDS_FOLDER"
+    search_path="$PROJECTR_COMMANDS_FOLDER/project"
     argument_combination="$search_path/$1"
     while [[ -n "$@" ]]
     do
         # pop the first argument off
         shift 1
-        for each in $(find "$search_path" -maxdepth 1 ! -path .)
+        for each in "$search_path/"**/*
         do
-            if [[ "$(absolute_path "$argument_combination")" = "$(absolute_path "$each")" ]]
+            if [[ "$argument_combination" = "$each" ]]
             then
                 # if its a folder, then we need to go deeper
                 if [[ -d "$each" ]]
@@ -61,8 +99,8 @@ else
             fi
         done
     done
-    printf "\nI could not find that command\n" 1>&2
+    printf "\nI could not find that project command\n" 1>&2
     printf "Valid options are:\n" 1>&2
-    ls -1 "$search_path" | sed 's/^/    /' 1>&2
+    ls -1 --color -F "$search_path" | sed 's/^/    /' 1>&2
     exit 1 # error, no command
 fi
