trying color round 3

diff --git a/settings/extensions/nix/installer_helper b/settings/extensions/nix/installer_helper
--- a/settings/extensions/nix/installer_helper
+++ b/settings/extensions/nix/installer_helper
@@ -122,128 +122,126 @@ else
             echo "one moment please ..."
             color_reset="\e[0m"
             echo "$color_reset"
-            export repo
-            export branch
             # run everything in a nix shell for reliability
-            nix-shell --quiet --packages bash git --run ' bash -c '"'"'
-                echo "It looks like you are inside an existing project"
-                # ask about mixing in another repository
-                question="Do you want to combine (mixin) another repository into this project? [y/n]";answer=""
-                while true; do
-                    echo "$question"; read response
-                    case "$response" in
-                        [Yy]* ) answer="yes"; break;;
-                        [Nn]* ) answer="no"; break;;
-                        * ) echo "Please answer yes or no";;
-                    esac
-                done
-                if [ "$answer" = "yes" ]
+            echo "It looks like you are inside an existing project"
+            # ask about mixing in another repository
+            light_green="\e[0;1;32m"
+            color_reset="\e[0m"
+            question="${light_green}Do you want to combine (mixin) another repository into this project? [y/n]${color_reset}";answer=""
+            while true; do
+                echo "$question"; read response
+                case "$response" in
+                    [Yy]* ) answer="yes"; break;;
+                    [Nn]* ) answer="no"; break;;
+                    * ) echo "Please answer yes or no";;
+                esac
+            done
+            if [ "$answer" = "yes" ]
+            then
+                if [ -z "$repo" ]
                 then
-                    if [ -z "$repo" ]
-                    then
-                        repo="https://github.com/jeff-hykin/fornix"
-                        light_green="\e[0;1;32m"
-                        echo "$light_green"
-                        echo "What is the URL of the repository?"
-                        cyan="\e[0;36m"
-                        echo "$cyan"
-                        echo "(press enter to go with the default: $repo)"
-                        color_reset="\e[0m"
-                        echo "$color_reset"
-                        read answer
-                        if [ -n "$answer" ]
-                        then
-                            repo="$answer"
-                        fi
-                    fi
-                    
-                    # 
-                    # get branch
-                    # 
-                    if [ -z "$branch" ]
-                    then
-                        branch="master"
-                        light_green="\e[0;1;32m"
-                        echo "$light_green"
-                        echo "Which branch would you like to get?"
-                        cyan="\e[0;36m"
-                        echo "$cyan"
-                        echo "(press enter to go with the default: $branch)"
-                        color_reset="\e[0m"
-                        echo "$color_reset"
-                        read answer
-                        if [ -n "$answer" ]
-                        then
-                            branch="$answer"
-                        fi
-                    fi
-                    
-                    # 
-                    # get mixin name
-                    # 
-                    name_for_upstream="@mixin"
+                    repo="https://github.com/jeff-hykin/fornix"
                     light_green="\e[0;1;32m"
                     echo "$light_green"
-                    echo "inside this project what should we call this mixin source?"
+                    echo "What is the URL of the repository?"
                     cyan="\e[0;36m"
                     echo "$cyan"
-                    echo "(press enter to go with the default: $name_for_upstream)"
+                    echo "(press enter to go with the default: $repo)"
                     color_reset="\e[0m"
                     echo "$color_reset"
                     read answer
                     if [ -n "$answer" ]
                     then
-                        name_for_upstream="$answer"
-                    fi
-                    
-                    # 
-                    # perform the mixin
-                    # 
-                    # clear out anything that used to be there
-                    git remote remove "$name_for_upstream" 2>/dev/null 1>/dev/null
-                    # add it as a remote and start merging
-                    git remote add "$name_for_upstream" "$repo" && \
-                        git fetch "$name_for_upstream" "$branch" && \
-                        git pull --allow-unrelated-histories "$name_for_upstream" "$branch" && \
-                        git submodule update --init --recursive
-                    
-                    # if failed
-                    if [ "$?" != "0" ]
-                    then
-                        light_red="\e[0;1;31m"
-                        echo "$light_red"
-                        echo "There was a problem :/"
-                        echo "    looks like git could not add that mixin"
-                        echo "    make sure the URL and branch name are correct"
-                        echo "    if they are correct, then hopefully there is error output above that"
-                        echo "    will give you a better idea as to why git could not get the repo"
-                    else
-                        # check for conflicts
-                        if [ -n "$(git status | grep "You have unmerged paths.")" ]
-                        then
-                            echo ""
-                            light_yellow="\e[0;1;33m"
-                            echo "$light_yellow"
-                            echo "Looks like you have a merge conflict"
-                            color_reset="\e[0m"
-                            echo "$color_reset"
-                            echo "(no big deal)"
-                            echo "Get the merge finished, and the mixin will be complete!"
-                            light_purple="\e[0;1;35m"
-                            echo "$light_purple"
-                            echo "Not sure how to resolve a merge conflict?"
-                            color_reset="\e[0m"
-                            echo "$color_reset"
-                            echo "     how to resolve merge conflicts in VS Code: https://www.youtube.com/watch?v=QmKdodJU-js"
-                            echo "     how to resolve merge conflicts in command line: https://phoenixnap.com/kb/how-to-resolve-merge-conflicts-in-git"
-                        else
-                            echo ""
-                            echo "Looks like the mixin was successful!"
-                            echo "You can probably use `commands/start` to get into the project env now"
-                        fi
+                        repo="$answer"
                     fi
                 fi
-            '"'"''
+                
+                # 
+                # get branch
+                # 
+                if [ -z "$branch" ]
+                then
+                    branch="master"
+                    light_green="\e[0;1;32m"
+                    echo "$light_green"
+                    echo "Which branch would you like to get?"
+                    cyan="\e[0;36m"
+                    echo "$cyan"
+                    echo "(press enter to go with the default: $branch)"
+                    color_reset="\e[0m"
+                    echo "$color_reset"
+                    read answer
+                    if [ -n "$answer" ]
+                    then
+                        branch="$answer"
+                    fi
+                fi
+                
+                # 
+                # get mixin name
+                # 
+                name_for_upstream="@mixin"
+                light_green="\e[0;1;32m"
+                echo "$light_green"
+                echo "inside this project what should we call this mixin source?"
+                cyan="\e[0;36m"
+                echo "$cyan"
+                echo "(press enter to go with the default: $name_for_upstream)"
+                color_reset="\e[0m"
+                echo "$color_reset"
+                read answer
+                if [ -n "$answer" ]
+                then
+                    name_for_upstream="$answer"
+                fi
+                
+                # 
+                # perform the mixin
+                # 
+                # clear out anything that used to be there
+                git remote remove "$name_for_upstream" 2>/dev/null 1>/dev/null
+                # add it as a remote and start merging
+                git remote add "$name_for_upstream" "$repo" && \
+                    git fetch "$name_for_upstream" "$branch" && \
+                    git pull --allow-unrelated-histories "$name_for_upstream" "$branch" && \
+                    git submodule update --init --recursive
+                
+                # if failed
+                if [ "$?" != "0" ]
+                then
+                    light_red="\e[0;1;31m"
+                    echo "$light_red"
+                    echo "There was a problem :/"
+                    echo "    looks like git could not add that mixin"
+                    echo "    make sure the URL and branch name are correct"
+                    echo "    if they are correct, then hopefully there is error output above that"
+                    echo "    will give you a better idea as to why git could not get the repo"
+                else
+                    # check for conflicts
+                    if [ -n "$(git status | grep "You have unmerged paths.")" ]
+                    then
+                        echo ""
+                        light_yellow="\e[0;1;33m"
+                        echo "$light_yellow"
+                        echo "Looks like you have a merge conflict"
+                        color_reset="\e[0m"
+                        echo "$color_reset"
+                        echo "(no big deal)"
+                        echo "Get the merge finished, and the mixin will be complete!"
+                        light_purple="\e[0;1;35m"
+                        echo "$light_purple"
+                        echo "Not sure how to resolve a merge conflict?"
+                        color_reset="\e[0m"
+                        echo "$color_reset"
+                        echo "     how to resolve merge conflicts in VS Code: https://www.youtube.com/watch?v=QmKdodJU-js"
+                        echo "     how to resolve merge conflicts in command line: https://phoenixnap.com/kb/how-to-resolve-merge-conflicts-in-git"
+                    else
+                        echo ""
+                        echo "Looks like the mixin was successful!"
+                        echo "You can probably use `commands/start` to get into the project env now"
+                    fi
+                fi
+            fi
         # 
         # setup or copy
         # 
